#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $)"/..

# find the installers and run them iteratively
find . -name .git -prune -o -name install.sh -print | while read installer ; do sh -c "${installer}" ; done
